<a href="https://colab.research.google.com/github/ksbisht941/ai-engineer/blob/master/2_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1: 10, 2: 20, 3: 30}

# Series

In [ ]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=d)

1    10
2    20
3    30
dtype: int64

# DataFrame

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
# df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
df2.columns = ['Name', 'Age', 'City', 'Salary']
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selection and Indexing of Columns

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [ ]:
df2[['Name', 'Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

# Create New Column

In [ ]:
df2['Designation'] = ["Manager", "Developer", "Designer", "Tester"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000     Manager
1   Anna   34     Paris   70000   Developer
2  Peter   29    Berlin   62000    Designer
3  Linda   42    London   85000      Tester

# Remove a Column

In [ ]:
df2.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop('Designation', axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selecting Rows

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[0]]

   Name  Age      City  Salary
0  John   28  New York   65000

In [ ]:
df2.loc[[0, 1, 3]]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
3  Linda   42    London   85000

In [ ]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# Selecting Subsets of Rows and Column

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[0, 1]][['Name', 'Age']]

   Name  Age
0  John   28
1  Anna   34

In [ ]:
df2.loc[[2, 3]][['Name', 'City']]

    Name    City
2  Peter  Berlin
3  Linda  London

# Conditional Selections

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

# Removing Missing Data

In [ ]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

# Filling Missing Data

In [ ]:
df.fillna(value=0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
value={ 'A': 10, 'B': 20, 'C': 30, 'D': 40 }
df.fillna(value=value)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  40.0
2  10.0  3   3.0  40.0
3   4.0  4  30.0  40.0
4   5.0  5  30.0   5.0

In [ ]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# Merging 2 dataframes

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

# Concatination of 2 DataFrames

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'D': ['A3', 'A4', 'A5'],
    'E': ['B3', 'B4', 'B5'],
    'F': ['C3', 'C4', 'C5']
})

In [ ]:
pd.concat([df1, df2])

     A    B    C    D    E    F
0   A0   B0   C0  NaN  NaN  NaN
1   A1   B1   C1  NaN  NaN  NaN
2   A2   B2   C2  NaN  NaN  NaN
0  NaN  NaN  NaN   A3   B3   C3
1  NaN  NaN  NaN   A4   B4   C4
2  NaN  NaN  NaN   A5   B5   C5

In [ ]:
pd.concat([df1, df2], axis=1)

    A   B   C   D   E   F
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Joining 2 data frames

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    D   E   F
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
df1.join(df2,how='outer')

    A   B   C   D   E   F
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
df1.join(df2,how='inner')

    A   B   C   D   E   F
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
df2.join(df1,how='outer')

    D   E   F   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

In [ ]:
df2.join(df1,how='inner')

    D   E   F   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

In [ ]:
df1.join(df2)

    A   B   C   D   E   F
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
df2.join(df1)

    D   E   F   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

# GroupBy

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [ ]:
"""mean median min max count std """
df['Sales'].mean()

np.float64(187.5)

In [ ]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [ ]:
# df.describe()

# Pivot Tables

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    875     42   John
1  2023-01-02       B   West    245     88   Mary
2  2023-01-03       C  North    302     61    Bob
3  2023-01-04       D  South    118     69  Alice
4  2023-01-05       A   East    597     12   John
5  2023-01-06       B   West    707     52   Mary
6  2023-01-07       C  North    264     86    Bob
7  2023-01-08       D  South    409     74  Alice
8  2023-01-09       A   East    441     43   John
9  2023-01-10       B   West    439     57   Mary
10 2023-01-11       C  North    496     44    Bob
11 2023-01-12       D  South    768     67  Alice
12 2023-01-13       A   East    155     16   John
13 2023-01-14       B   West    908     78   Mary
14 2023-01-15       C  North    135     96    Bob
15 2023-01-16       D  South    365     88  Alice
16 2023-01-17       A   East    181     53   John
17 2023-01-18       B   West    513     58   Mary
18 2023-01-19       C  North    892     26    Bob
19 2023-01-20       D  South    581     99  Alice

In [ ]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    365     53   John  January      Q1
1  2023-01-02       B   West    539     84   Mary  January      Q1
2  2023-01-03       C  North    990     98    Bob  January      Q1
3  2023-01-04       D  South    704     46  Alice  January      Q1
4  2023-01-05       A   East    169     31   John  January      Q1
5  2023-01-06       B   West    231     13   Mary  January      Q1
6  2023-01-07       C  North    936     61    Bob  January      Q1
7  2023-01-08       D  South    372     88  Alice  January      Q1
8  2023-01-09       A   East    673     64   John  January      Q1
9  2023-01-10       B   West    566     19   Mary  January      Q1
10 2023-01-11       C  North    392     61    Bob  January      Q1
11 2023-01-12       D  South    488     24  Alice  January      Q1
12 2023-01-13       A   East    816     36   John  January      Q1
13 2023-01-14       B   West    539     10   Mary  January      Q1
14 2023-01-15       C  North    404     81    Bob  January      Q1
15 2023-01-16       D  South    880     16  Alice  January      Q1
16 2023-01-17       A   East    478     62   John  January      Q1
17 2023-01-18       B   West    450     39   Mary  January      Q1
18 2023-01-19       C  North    578     42    Bob  January      Q1
19 2023-01-20       D  South    518     70  Alice  January      Q1

In [ ]:
df.groupby('Region')['Sales'].median()

Region
East     441.0
North    302.0
South    409.0
West     513.0
Name: Sales, dtype: float64

In [ ]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     441.0    NaN    NaN    NaN
North      NaN    NaN  302.0    NaN
South      NaN    NaN    NaN  409.0
West       NaN  513.0    NaN    NaN

In [ ]:
pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     449.8    NaN    NaN    NaN  33.2   NaN   NaN   NaN
North      NaN    NaN  417.8    NaN   NaN   NaN  62.6   NaN
South      NaN    NaN    NaN  448.2   NaN   NaN   NaN  79.4
West       NaN  562.4    NaN    NaN   NaN  66.6   NaN   NaN

# Cross Tabs

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0