In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1: 10, 2: 20, 3: 30}

# Series

In [ ]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=d)

1    10
2    20
3    30
dtype: int64

# DataFrame

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
# df2 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
df2.columns = ['Name', 'Age', 'City', 'Salary']
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000