# Selection and Indexing of Columns

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [ ]:
df2[['Name', 'Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

# Create New Column

In [ ]:
df2['Designation'] = ["Manager", "Developer", "Designer", "Tester"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000     Manager
1   Anna   34     Paris   70000   Developer
2  Peter   29    Berlin   62000    Designer
3  Linda   42    London   85000      Tester

# Remove a Column

In [ ]:
df2.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop('Designation', axis=1, inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# Selecting Rows

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[0]]

   Name  Age      City  Salary
0  John   28  New York   65000

In [ ]:
df2.loc[[0, 1, 3]]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
3  Linda   42    London   85000

In [ ]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# Selecting Subsets of Rows and Column

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[0, 1]][['Name', 'Age']]

   Name  Age
0  John   28
1  Anna   34

In [ ]:
df2.loc[[2, 3]][['Name', 'City']]

    Name    City
2  Peter  Berlin
3  Linda  London

# Conditional Selections

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000