# GroupBy

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [ ]:
"""mean median min max count std """
df['Sales'].mean()

np.float64(187.5)

In [ ]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [ ]:
# df.describe()

# Pivot Tables

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    875     42   John
1  2023-01-02       B   West    245     88   Mary
2  2023-01-03       C  North    302     61    Bob
3  2023-01-04       D  South    118     69  Alice
4  2023-01-05       A   East    597     12   John
5  2023-01-06       B   West    707     52   Mary
6  2023-01-07       C  North    264     86    Bob
7  2023-01-08       D  South    409     74  Alice
8  2023-01-09       A   East    441     43   John
9  2023-01-10       B   West    439     57   Mary
10 2023-01-11       C  North    496     44    Bob
11 2023-01-12       D  South    768     67  Alice
12 2023-01-13       A   East    155     16   John
13 2023-01-14       B   West    908     78   Mary
14 2023-01-15       C  North    135     96    Bob
15 2023-01-16       D  South    365     88  Alice
16 2023-01-17       A   East    181     53   John
17 2023-01-18       B   West    513     58   Mary
18 2023-01-19       C  North    892     26    Bob
19 2023-01-20       D  South    581     99  Alice

In [ ]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    365     53   John  January      Q1
1  2023-01-02       B   West    539     84   Mary  January      Q1
2  2023-01-03       C  North    990     98    Bob  January      Q1
3  2023-01-04       D  South    704     46  Alice  January      Q1
4  2023-01-05       A   East    169     31   John  January      Q1
5  2023-01-06       B   West    231     13   Mary  January      Q1
6  2023-01-07       C  North    936     61    Bob  January      Q1
7  2023-01-08       D  South    372     88  Alice  January      Q1
8  2023-01-09       A   East    673     64   John  January      Q1
9  2023-01-10       B   West    566     19   Mary  January      Q1
10 2023-01-11       C  North    392     61    Bob  January      Q1
11 2023-01-12       D  South    488     24  Alice  January      Q1
12 2023-01-13       A   East    816     36   John  January      Q1
13 2023-01-14       B   West    539     10   Mary  January      Q1
14 2023-01-15       C  North    404     81    Bob  January      Q1
15 2023-01-16       D  South    880     16  Alice  January      Q1
16 2023-01-17       A   East    478     62   John  January      Q1
17 2023-01-18       B   West    450     39   Mary  January      Q1
18 2023-01-19       C  North    578     42    Bob  January      Q1
19 2023-01-20       D  South    518     70  Alice  January      Q1

In [ ]:
df.groupby('Region')['Sales'].median()

Region
East     441.0
North    302.0
South    409.0
West     513.0
Name: Sales, dtype: float64

In [ ]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     441.0    NaN    NaN    NaN
North      NaN    NaN  302.0    NaN
South      NaN    NaN    NaN  409.0
West       NaN  513.0    NaN    NaN

In [ ]:
pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     449.8    NaN    NaN    NaN  33.2   NaN   NaN   NaN
North      NaN    NaN  417.8    NaN   NaN   NaN  62.6   NaN
South      NaN    NaN    NaN  448.2   NaN   NaN   NaN  79.4
West       NaN  562.4    NaN    NaN   NaN  66.6   NaN   NaN

# Cross Tabs

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0