In [4]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [5]:
df = pd.read_csv("../datasets/data.csv")
df.head()

    Age   Salary  Experience       City
0  25.0  50000.0         2.0      Delhi
1  30.0      NaN         5.0     Mumbai
2   NaN  60000.0         7.0      Delhi
3  35.0  65000.0         NaN  Bangalore
4  40.0  70000.0        10.0        NaN

In [6]:
num_cols = ["Age", "Salary", "Experience"]
cat_cols = ["City"]

In [7]:
# Numeric → median
num_imputer = SimpleImputer(strategy="median")
df[num_cols] = num_imputer.fit_transform(df[num_cols])

In [8]:
# Categorical → most frequent
# cat_imputer = SimpleImputer(strategy="most_frequent")
cat_imputer = SimpleImputer(strategy='constant',fill_value="Unknown")
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

In [9]:
df.head(5)

    Age   Salary  Experience       City
0  25.0  50000.0         2.0      Delhi
1  30.0  66000.0         5.0     Mumbai
2  35.5  60000.0         7.0      Delhi
3  35.0  65000.0         8.5  Bangalore
4  40.0  70000.0        10.0    Unknown